{
 "title": "Pipeline",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Recent Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"grex_t0\"} |= ``"
    }
   ]
  },
  {
   "title": "21cm SNR",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max_over_time(spectrum{channel=\"897\", polarization=\"stokes\"}[20m])",
     "legendFormat": "peak_flux"
    },
    {
     "expr": "stddev_over_time(spectrum{channel=\"905\", polarization=\"stokes\"}[20m])",
     "legendFormat": "std_noise"
    },
    {
     "expr": "avg_over_time(spectrum{channel=\"905\", polarization=\"stokes\"}[20m])",
     "legendFormat": "mean_noise"
    }
   ]
  },
  {
   "title": "Current 21cm SNR",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(spectrum{channel=\"897\", polarization=\"stokes\"}[20m])",
     "legendFormat": "peak_flux"
    },
    {
     "expr": "stddev_over_time(spectrum{channel=\"905\", polarization=\"stokes\"}[20m])",
     "legendFormat": "std_noise"
    },
    {
     "expr": "avg_over_time(spectrum{channel=\"905\", polarization=\"stokes\"}[20m])",
     "legendFormat": "mean_noise"
    }
   ]
  },
  { "title": "FPGA Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "ADC RMS Value",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "adc_rms{instance=\"host.docker.internal:8083\"}",
     "legendFormat": "Channel {{channel}}"
    }
   ]
  },
  {
   "title": "ADC RMS Value Histogram",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "adc_rms{instance=\"host.docker.internal:8083\"}",
     "legendFormat": "Channel {{channel}}"
    }
   ]
  },
  {
   "title": "Overflow Counts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Counts" } },
   "targets": [
    {
     "expr": "rate(fft_ovfl{instance=\"host.docker.internal:8083\"}[$__rate_interval])",
     "legendFormat": "FFT"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "fpga_temp{instance=\"host.docker.internal:8083\"}",
     "legendFormat": "FPGA"
    }
   ]
  },
  { "title": "Task Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Processed Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(processed_packets{instance=\"host.docker.internal:8083\"}[$__rate_interval])",
     "legendFormat": "Processed"
    }
   ]
  },
  {
   "title": "Current Dropped Packet Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dropped_packets{instance=\"host.docker.internal:8083\"} / processed_packets{instance=\"host.docker.internal:8083\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(dropped_packets{instance=\"host.docker.internal:8083\"}[$__rate_interval])",
     "legendFormat": "Drops"
    },
    {
     "expr": "rate(shuffled_packets{instance=\"host.docker.internal:8083\"}[$__rate_interval])",
     "legendFormat": "Out of Order"
    }
   ]
  },
  { "title": "Spectrum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Last Spectra",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "spectrum{polarization=\"a\", instance=\"host.docker.internal:8083\"}",
     "legendFormat": "A"
    },
    {
     "expr": "spectrum{polarization=\"b\", instance=\"host.docker.internal:8083\"}",
     "legendFormat": "B"
    }
   ]
  },
  {
   "title": "Last Stokes",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "spectrum{polarization=\"stokes\", instance=\"host.docker.internal:8083\"}",
     "legendFormat": "A"
    }
   ]
  }
 ]
}